### ISSUE TITLE
Workflow broken

### ISSUE THREAD

**Issue by eweracs** [alexander-heimbuch/deepl-alfred-workflow#4]
Hi, I came across this workflow on my search for the best DeepL Alfred integration. Sadly, although it looks incredibly useful, the workflow doesn't seem to work anymore. I get "Search deepl for '...' ", and when I enter my query, nothing comes up and Alfred exits the workflow, only offering to search google for my input. Any possibility this is an issue on my end?

**Comment by alexander-heimbuch** [comment]
Unfortunately DeepL cut off the way this flow is working since it kind of bypasses the API. So I don't think that this flow will work without a proper API client, but this can be very pricy so I don't see any working Alfred integration in the near future.

**Comment by eweracs** [comment]
Thank you very much for your explanation, that's a shame to hear, but understandable. Appreciate your efforts, though!
